openapi: 3.0.0
info:
  title: API REST
  description: Uma API REST desenvolvida com Express.
  version: 0.1.0
servers: 
  - url: http://localhost:3000
    description: Ambiente de desenvolvimento
tags:
  - name: produtos
paths:
  /produtos:
    get:
      tags:
        - produtos
    post:
      tags:
        - produtos
  /produtos/{produtoId}:
    get:
     tags:
        - produtos
    put:
      tags:
        - produtos
    delete:
      tags:
       - produtos
components:
